### ISSUE TITLE
Update plugins to the latest version

### ISSUE THREAD

**Issue by jm-kumaresh** [vlrprbttst/BoxTent#3]
Hi I'm newbie to grunt and sass. Is it possible to update the **devDependencies** to the latest version and copy the updated files to the **dev**  folder.

For example I'm having the jquery 1.9.1 as devDependencies and I would like to update the jquery to the latest version and copy that to the directory **_dev>js>libs**. So that whenever there is a newer version of plugins the attached scripts will be updated to the latest version. Is it possible..?

Kumaresh

**Comment by vlrprbttst** [comment]
@jm-kumaresh sure thing. you can open the `bower.json` file before installing the dependencies, change the version number of jQuery manually, save and then type `bower install` on your terminal. you should get the jQuery version you wanted. Don't forget to follow these instructions when you're done:

> if you install a new js library with bower, be sure to include its path in the copy:bower and the concat:dist tasks of the gruntfile. Once done, type grunt copy:bower from the shell to move them in your project. Don't forget to reference them at the bottom of your .html files including them inside the processhtml special comments

**Comment by jm-kumaresh** [comment]
@vlrprbttst Thanks for the reply. Doesn't we automate the process of checking for new version and add it automatically instead of changing the version number of jQuery manually..?

**Comment by vlrprbttst** [comment]
using one version or another of jquery is kind of personal. newer jquery dropped IE6 support for example and you might need that. I think it's best to include a stable version of jquery leaving the possibility to the user to choose another one if they want.

another way of installing the latest jquery would have been to type `bower uninstall jquery --save-dev` and then `bower install jquery --save-dev` and you would have got the latest.

more on this here: https://jquery.com/download/#downloading-jquery-using-bower
