### ISSUE TITLE
Issue on _dev folder update

### ISSUE THREAD

**Issue by jm-kumaresh** [vlrprbttst/BoxTent#4]
There was issue with updating **_dev** folder file while I make changes on **_src** folder HTML or CSS. Whenever I make changes on **_src** folder the command line shows the files updated. But the changes are not updated on browser. Also I tried checking the **_dev** folder files for the updates. But the changes are not there in the files.

![boxtent](https://cloud.githubusercontent.com/assets/2070512/16447830/0c6e4d6a-3e0c-11e6-9fda-3818fc2259f2.jpg)

Not sure this issue is because of Critical CSS.
## 

Kumaresh

**Comment by jm-kumaresh** [comment]
Is that due to `grunt-newer` package ..?

**Comment by vlrprbttst** [comment]
_includes are not watched as they are processed when the html file including them is updated and saved. If you change the html of an include, save it, then open the html file that includes it and save that as well to trigger the `processhtml` task.

thanks for opening the issues, this let's me have a clearer idea of bugs or stuff i can improve 👍

**Comment by jm-kumaresh** [comment]
is there is any way to add those _includes to watched..?

**Comment by vlrprbttst** [comment]
try removing this `, '!_includes/**/*.html'` from the `gruntfile.js` but I'm not sure if this works because of processhtml logics

**Comment by vlrprbttst** [comment]
@jm-kumaresh did it work?

**Comment by jm-kumaresh** [comment]
@vlrprbttst No luck. It's not working. Every time I have to save the index.html to reflect the changes in browser.

**Comment by jm-kumaresh** [comment]
@vlrprbttst I'm looking to use [Tars](https://github.com/tars/tars) due to this issue.

**Comment by vlrprbttst** [comment]
by the way this is solved on this commit: https://github.com/vlrprbttst/BoxTent/commit/0f725aecc0851157ec4d988cc1f0b8434b054add#diff-595bf3fa2348192244b0319be33066b8R53 (you can easily update your gruntfile accordingly).

now the browser refreshes on includes changes as well @jm-kumaresh - that was both the `, '!_includes/**/*.html'` and the `newer` task.

the only problem now is that processhtml will process _all_ files each time an html file changes, which is not exactly the best if you have a lot of html pages in your project. this may slow down the build time a bit.

**Comment by jm-kumaresh** [comment]
@vlrprbttst Thanks for the update.

**Comment by jm-kumaresh** [comment]
Hi @vlrprbttst . Just confirming that above issue was fixed. Because [boxtent website](http://www.boxtent.top/) mentions that _includes are not watched.

**Comment by vlrprbttst** [comment]
@jm-kumaresh i rolled that back because i've noticed that watching includes triggers processhtml bringing the includes folder and its files in both _dev and _site, which is not a bug but not the desired behavior either. I should come back at this in the future though. thanks! 👍

**Comment by jm-kumaresh** [comment]
Thanks. Hope this will be fixed in future.

And is there is any reason why node modules are more than 80MB..? Can't we reduce the size..? If i create multiple projects, each project occupies the additional disk space.

**Comment by vlrprbttst** [comment]
@jm-kumaresh that's not something in my power unfortunatly. BoxTent has a lot of dependencies and each dependency (and its cached files) takes up some space
